# Generated by Django 4.1.2 on 2023-06-29 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaProducto',
            fields=[
                ('idArea', models.AutoField(db_column='idArea', primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('descripcion', models.CharField(max_length=50, verbose_name='descripcion')),
                ('precio', models.IntegerField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='images')),
                ('idArea', models.ForeignKey(db_column='idArea', on_delete=django.db.models.deletion.CASCADE, to='harry_potter.areaproducto', verbose_name='idArea')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
