# Generated by Django 4.1.2 on 2023-07-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harry_potter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='id',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='img',
        ),
        migrations.AddField(
            model_name='productos',
            name='codigo',
            field=models.CharField(default='valor_predeterminado', max_length=6, primary_key=True, serialize=False, verbose_name='codigo'),
        ),
        migrations.AddField(
            model_name='productos',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='Img/', verbose_name='Img'),
        ),
    ]
