# Generated by Django 4.1.2 on 2023-07-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harry_potter', '0002_remove_productos_id_remove_productos_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='codigo',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='codigo'),
        ),
    ]
